security:
    providers:
        eulogin:
            id: eulogin.userprovider
    firewalls:
        default:
            guard:
                authenticators:
                    - cas.guardauthenticator
                provider: eulogin
